### ISSUE TITLE
Reset cloth button

### ISSUE THREAD

**Issue by CrazyPython** [Dissimulate/Tearable-Cloth#6]

**Comment by Radi123** [comment]
I want to help ...
I will create pull request, soon....

**Comment by radi-cho** [comment]
@CrazyPython There is ```reset``` button in Tearable-Cloth v2
http://codepen.io/dissimulate/details/eZxEBO/
![image](https://cloud.githubusercontent.com/assets/12954909/24838378/7596e432-1d4f-11e7-937b-ffcfdf1a316e.png)
